version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000 # Incorrect or missing package comment.
        - -ST1005 # Incorrectly formatted error string.
  exclusions:
    presets:
      - std-error-handling
