---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: skopeo
upstream_tag_template: v{version}

specfile_path: skopeo.spec

# Disable automatic merging for Copr builds (and subsequent Testing Farm)
merge_pr_in_ci: false

jobs:
  - job: copr_build
    trigger: pull_request
    notifications: &packit_failure_notification
      failure_comment:
        message: "Packit jobs failed. @containers/packit-build please check."
    enable_net: true
    targets:
      - epel-10-x86_64
      - epel-10-aarch64
    actions:
      post-upstream-clone: "curl --fail -O https://gitlab.com/redhat/centos-stream/rpms/skopeo/-/raw/c10s/skopeo.spec"

  - job: copr_build
    trigger: pull_request
    notifications: *packit_failure_notification
    enable_net: true
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
    actions:
      post-upstream-clone: "curl --fail -O https://gitlab.com/redhat/centos-stream/rpms/skopeo/-/raw/c9s/skopeo.spec"

  - job: tests
    trigger: pull_request
    use_internal_tf: true
    notifications: *packit_failure_notification
    targets:
      epel-10-x86_64:
        distros: [RHEL-10-Nightly,RHEL-10.0-Nightly]
      epel-10-aarch64:
        distros: [RHEL-10-Nightly,RHEL-10.0-Nightly]
      epel-9-x86_64:
        distros: [RHEL-9-Nightly,RHEL-9.6.0-Nightly]
      epel-9-aarch64:
        distros: [RHEL-9-Nightly,RHEL-9.6.0-Nightly]
    tmt_plan: "/plans/system"
    identifier: "rpm"

  - job: tests
    trigger: pull_request
    use_internal_tf: true
    notifications: *packit_failure_notification
    skip_build: true
    targets:
      epel-10-x86_64:
        distros: [RHEL-10-Nightly,RHEL-10.0-Nightly]
      epel-9-x86_64:
        distros: [RHEL-9-Nightly,RHEL-9.6.0-Nightly]
    tmt_plan: "/plans/no-rpm"
    identifier: "no-rpm"
